services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit-mti-echappement
    ports:
      - "1025:1025"  # Port SMTP
      - "8025:8025"  # Interface Web
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    restart: unless-stopped
